### PR TITLE
New Member-21 - my solution

### PR DESCRIPTION
**Pull request by simoneferrero**
I have created two functions, one to find the divisors of an integer, the other to check if that integer is abundant, deficient or perfect.
I have called them for both arguments in the main function deficientlyAbundantAmicableNumbers(num1, num2).
I have pushed the results in an array and returned it as a string.
I realise that using an array is not mandatory in this case, but I like working with arrays when I can as I find them easier to read and modify.

Since it is the first time I'm using GitHub, I hope I am following the guidelines accordingly, please let me know if there is something I should have done differently.
Thanks!

### CODE REVIEW

**Comment by GiacomoSorbi** [comment]
Performance-wise, I would not check until number-1; also, the functions would make more sense in terms of maintainability returning a value instead of pushing into an array (the latter is just my personal taste).

Kudos for properly commenting your code \m/!

**Comment by simoneferrero** [comment]
Thanks for your comment!
I know I rely too much on arrays, I find them easier to work with at this stage as I'm getting to know more methods, and I can exercise even with simple functions as this one. I am planning on reducing my addiction to arrays when I'm more comfortable with the language :)

I'm sorry but I did not understand your suggestion "I would not check until number-1", could you please explain it further?
Thanks!

**Comment by GiacomoSorbi** [comment]
Sure thing, dear sir: to find the divisors of n, it is quite pointless (and inefficient) to check up to n-1.

Assume you have to find the divisors of 12: does it makes sense to check for 7, 8, 9, 10, 11? I would presume not that much.

I would go for a dynamic array using memoization and a clever Sieve of Eratosthenes algo (checking only number in the format 6k-1 and 6k+1), but that would be an overkill and by itself would be much, MUCH more difficult than solving this kata itself (just to let you know you could go that way, basically).

**Comment by simoneferrero** [comment]
I see, thanks for the clarification! I looked at it on StackOverflow and yeah, it looks a little over my capabilities, at least for now :)

**Comment by GiacomoSorbi** [comment]
Oh, it just takes a few days of practice, nothing transcendental and I think we will discuss it soon live in our session, if you ever stumble by London on Monday ;)

**Comment by RichAWarren** [comment]
Good answer- A much easiear performance cheat would be to only loop up until x <= number/2 when finding divisors!

**Comment by simoneferrero** [comment]
True, I guess I still have to learn some logic :)
Thank you both for your comments, I'll see you on Monday then!

**Pull request merged**
