### PR TITLE
solution to new-member-19

### PR DESCRIPTION
**Pull request by davidnge**
This is solution to https://github.com/codingforeveryone/js/issues/90

### CODE REVIEW

**Comment by mcelearr** [comment]
Looks good to me! Nice use of filter function.

Super quick point.

```javascript
  if (newString == num.toString()){ 
    return true; 
    }
    
  else { 
    return false; 
    }
```
could be shortened to:
```javascript
return newString == num.toString()
```
Which would also return a boolean.

Nice work! :+1:

**Comment by davidnge** [comment]
wow, totally missed that, thanks for spotting!

**Comment by GiacomoSorbi** [comment]
Further shortening, if we play this game, then ;)

```return newString == ""+num```

**Comment by gabrielperales** [comment]
@GiacomoSorbi did you call me? :dancer: 

```javascript
const selfDescriptive = (num, start = 0) =>
	num == (''+num).split('').reduce((p)=>p+((''+num).match(new RegExp(start++,'g'))||[]).length, '');
```

**Comment by GiacomoSorbi** [comment]
Skip ```const```, among other things ;)

**Pull request merged**
