### PR TITLE
new-member-10-1-solution.js

### PR DESCRIPTION
**Pull request by tdowek1**

### CODE REVIEW

**Comment by gabrielperales** [comment]
I like your solution :+1: . It's a good approach to use a regex to remove non digit values from the string, but you could also use a regex for get only the digits of the string and then sum them.

**Comment by tdowek1** [comment]
Thanks for the feedback Gabriel!

Could you give me an example of the way that you would do it please? 

Regexp expressions have been the thing I have found it hardest to get my head around, but I feel I am getting there. 

Would really help to get as many examples as possible :).

**Comment by gabrielperales** [comment]
Of course. As you can see [here](https://github.com/gabrielperales/js/commit/32c7e920e92e67fe8ce8bb0ec1a0dd6934563a77) (It was my solution) I use the regex ```match(/\d/g)``` to get each digit (match function returns an array with all the coincidences), then I map digits to numbers, and finnally I sum them. Both approaches are very similar, but mine don't need to split the string :).

**Comment by gabrielperales** [comment]
I you want to learn more about regex, I did [this](https://www.codeschool.com/courses/breaking-the-ice-with-regular-expressions) course. I like codeschool, it's not free, and they are not the best courses, but they are interactive and easy to start with. I'll try to remember more regex resources :)

**Comment by tdowek1** [comment]
You're an absolute star Gabriel! Thank you!

**Comment by thevjm** [comment]
Looks good. Nice work! Please rename your file with a .js extension and I will merge your pull request.

**Comment by tdowek1** [comment]
I've changed the name now.

**Pull request merged**
