### PR TITLE
adding new-member-6 solution

### PR DESCRIPTION
**Pull request by philb56**
I am not sure whether this is all ok - the Github aspects not solution to problem 6. Any feedback appreciated.

### CODE REVIEW

**Comment by andrewMacmurray** [comment]
@philb56 that looks great, you've done everything (adding, committing, pushing to the branch and then made the pull request)

**Comment by andrewMacmurray** [comment]
Also nice clean solution

**Comment by philb56** [comment]
Thanks for the reassurance @andrewMacmurray - I feel a lot more comfortable about it now.

**Comment by andrewMacmurray** [comment]
@philb56 now worries! Git is quite intimidating at first (especially if you're not used to using the terminal, I definitely wasn't) but it becomes very powerful and useful once you get the hang of it, try it out on some of your projects if you get a chance

**Comment by andrewMacmurray** [comment]
The next thing to do will be if @franzmoro checks the solution to see if he's happy with it and then merges the pull request (will make the solution part of the master branch).

@philb56 if you could come up with a simple problem to solve (can be anything) and post it as an issue titled **new member #7**, that would be great.

**Comment by franzmoro** [comment]
Hi @philb56 . Good job! Your code works perfectly and also passes all tests in the Codewars [kata](http://www.codewars.com/kata/565b3542af398bfb50000003/train/javascript). I've merged your pull request.

**Comment by philb56** [comment]
Thank you @franzmoro. @andrewMacmurray I'll get right on to #7.

**Pull request merged**
