### PR TITLE
Updated README with a few links

### PR DESCRIPTION
**Pull request by JMurphyWeb**

### CODE REVIEW

**Comment by patrickwalkowicz** [comment]
Hi @JMurphyWeb looks like we're still having a conflict with this pull request. I've just spent some time trying to resolve it (and effectively pushed your changes into the repo using the command line). I had to do the following (quoting GitHub helper): 
```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b JMurphyWeb-master master
git pull https://github.com/JMurphyWeb/js.git master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff JMurphyWeb-master
git push origin master
```
It worked when I made sure that I operate on a clone of codingforeveryone/js, not patrickwalkowicz/js (lesson learned :smile: ). Also learned a thing or two about vim editor. I had to manually resolve the conflict in revertString.js and pushed back. Your readme file is pushed to codingforeveryone/js. However, I'm not sure if after doing all this this pull request is supposed to still be marked as having conflicts or not.

**Comment by Bektaz** [comment]
Hi @patrickwalkowicz, @JMurphyWeb I have also tried to understand what is the cause of this problem and found in stackoverflow [this](http://stackoverflow.com/questions/32030779/git-pull-request-says-this-branch-has-conflicts-that-must-be-resolved) explanation and solution, it may not be the best solution what I've found but it makes sense in terms of explanation. So in our repository currently we have two pull requests with conflict. One is this one the other one is 'Add a Gitter chat badge to README.md' which I've closed just now. I will merge it manually in local README.md file and push it later once we will be able to push changes to js repo. @patrickwalkowicz or @JMurphyWeb if this request is finished and is no active anymore let's close it manually. Then we will have mergeable,'working' requests remaining.

**Comment by patrickwalkowicz** [comment]
@JMurphyWeb, @Bektaz I took a liberty of closing the pull request. Previously, I've manually pushed your readme file as instructed on GitHub. It worked all right but the pull request status was still "not able to merge". Actually this is logical because your pull request still contained conflicting code for revertString.js that I resolved manually. Anyway, your changes are there and I think that's what matters.
Thanks, see you around, guys!

**Comment by Bektaz** [comment]
Thanks @patrickwalkowicz !

**Comment by JMurphyWeb** [comment]
Thanks! 
Any idea how i should avoid these sort of merge conflicts in the future.
Should we be using branches?

**Pull request closed without merging**
