### PR TITLE
should work

### PR DESCRIPTION
**Pull request by daymos**

### CODE REVIEW

**Comment by patrickwalkowicz** [comment]
Hi @daymos thanks for taking your time to work through the problem!

**Comment by daymos** [comment]
My pleasure, it was fun. I have seen you requested an upgrade, I´ll do it in the next days if nobody picks it

**Comment by patrickwalkowicz** [comment]
Take your time :+1: At the moment there's 3 people actively involved and that's including us both :smile: I'll be posting some new challenges soon.

**Comment by daymos** [comment]
ok!

**Pull request merged**
